# Generated by Django 4.0 on 2022-10-25 01:50

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_perfil', models.ImageField(blank=True, default='static/img/imgperfil/default.png', null=True, upload_to=registration.models.subir_avatar, verbose_name='ImgPerfil')),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Género')),
                ('tipo_documento', models.CharField(choices=[('Registro civil', 'Registro civil'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cedula de Ciudadania', 'Cedula de Ciudadania'), ('Cedula de Extrangeria', 'Cedula de Extrangeria'), ('Pasaporte', 'Pasaporte'), ('Permiso Especial', 'Permiso Especial'), ('Sin Identificar', 'Sin Identificar')], default='Sin Identificar', max_length=50, verbose_name='Tipo Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número Documento')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Teléfono')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('departamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil Usuario',
                'verbose_name_plural': 'Perfiles Usuarios',
                'ordering': ['usuario'],
            },
        ),
    ]
