# Generated by Django 4.0 on 2022-11-09 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_forma', models.CharField(choices=[('efectivo', 'efectivo'), ('pse', 'pse'), ('tarjeta credito', 'tarjeta credito'), ('transferencia', 'transferencia'), ('otro', 'otro')], default='otro', max_length=50, verbose_name='Forma de Pago')),
            ],
            options={
                'verbose_name_plural': 'Formas de pago',
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('Av Villas', 'Av Villas'), ('Bancolombia', 'Bancolombia'), ('BBVA', 'BBVA'), ('Banco Caja Social', 'Banco Caja Social'), ('Banco Davivienda', 'Banco Davivienda'), ('Banco de Bogota', 'Banco de Bogota'), ('Banco de Occidenete', 'Banco de Occidenete'), ('Banco Popular', 'Banco Popular'), ('Citibank', 'Citibank'), ('Itau', 'Itau'), ('Scotiabank ', 'Scotiabank '), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Banco')),
                ('cc_titular', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('titular', models.CharField(max_length=150, verbose_name='Nombre titular de la cuenta')),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total a Pagar')),
                ('iva_pago', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='IVA a pagar')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.formapago')),
            ],
            options={
                'verbose_name_plural': 'Detalle Pago',
            },
        ),
    ]
